#
# $Log: Makefile,v $
# Revision 1.1.1.1  2009/06/23 13:55:46  kawama
#
# e05115 src repository for software development
#
# Revision 1.1.1.1  2005/05/14 21:44:37  miyoshi
#
#
# Revision 1.1  2005/05/03 21:27:11  miyoshi
# newly added
#
# Revision 1.1  1998/12/07 22:11:25  saw
# Initial setup
#
ETC=../etc

include $(ETC)/Makefile.NEW
