#!/bin/sh

# Usage: farm_replay
#
# This script creates batch_krun and jscript_krun in batch_files directory
# and submits the job to the farms
#
# It assumes to be in the e01011-replay directory and the .tmpl.REPLAY file
# exists
#
# Updates
# November 02, 2006 Include recent changes due to Auger update
# July 18, 2005 Validate integer input
# July 10, 2005 Ask for the run number to the user VMR
# July 07, 2005 Victor M. Rodriguez
# Sep. 20, 2009 Zhihong Ye
#

# Function to check if input is an integer
#
RAWDIR=/w/cache/mss/hallc/hks09/raw/

is_integer() {
 case $1 in
  *[!0-9]*) return 1;;
  *) return 0;;
 esac
}
#
echo 
echo '***** Welcome to the auger script creator *****'
echo
#
# Verify if batch_files and .tmp.REPLAY exist
#
if ! [ -d batch_files ]
 then 
  echo 'I need batch_files directory. I am going to create it'
  echo  
  mkdir batch_files
fi

#
# Ask for the run number
#
krun=1

echo -n 'Which run do you want to submit? '
read krun
if ! is_integer "$krun" 
then
    echo 'Run number must be an integer or 0 to exit'
    echo 
    krun=1
else
    if [ "$krun" -eq 0 ]        # Type 0 to exit
    then exit 1
    fi
    if [ "$krun" -lt 75522 ] || [ "$krun" -gt 75441 ]
    then echo
	echo 'Now You are replaying Carbon Target data!~~~~'
	echo 
    fi
fi

echo 'Your process is being created...'
echo
#
home=$PWD                    # The directory where replay_script is
username=${USER}@jlab.org    # email which will be notify when the job is done
#
# Write file batch_krun
#
echo '#!/bin/sh' > batch_files/batch_$krun
echo 'cd ' $home >>batch_files/batch_$krun
echo './replay_script grun='$krun 'gstart=1 gstop=500000' >>batch_files/batch_$krun
echo 'mv ./paw/hks'$krun'.rzdat ./paw/hks'$krun'_1.rzdat' >>batch_files/batch_$krun
echo './replay_script grun='$krun 'gstart=500001 gstop=1000000' >>batch_files/batch_$krun
echo 'mv ./paw/hks'$krun'.rzdat ./paw/hks'$krun'_2.rzdat' >>batch_files/batch_$krun
echo './replay_script grun='$krun 'gstart=1000001 gstop=1500000' >>batch_files/batch_$krun
echo 'mv ./paw/hks'$krun'.rzdat ./paw/hks'$krun'_3.rzdat' >>batch_files/batch_$krun
echo './replay_script grun='$krun 'gstart=1500001 gstop=2000000' >>batch_files/batch_$krun
echo 'mv ./paw/hks'$krun'.rzdat ./paw/hks'$krun'_4.rzdat' >>batch_files/batch_$krun
chmod +x batch_files/batch_$krun
echo 'batch_files/batch_'${krun}' has been created!'
echo ' '
#
# Write the jsub script
#
echo 'PROJECT     e01011' > batch_files/jscript_$krun
echo 'COMMAND     '$home'/batch_files/batch_'$krun >>batch_files/jscript_$krun
echo 'JOBNAME     hks.analysis.'${krun} >>batch_files/jscript_$krun
echo 'TRACK       analysis' >> batch_files/jscript_$krun
echo 'TIME        4000' >>batch_files/jscript_$krun
echo 'OS          linux' >>batch_files/jscript_$krun
echo 'MAIL:       '$username >>batch_files/jscript_$krun
echo 'INPUT_FILES: '$home'/REPLAY.PARM' >>batch_files/jscript_$krun

#echo 'INPUT_FILES: '$RAWDIR'/hks09-coin_'$krun'.log.0' >>batch_files/jscript_$krun
#echo 'OTHER_FILES: '$home'/REPLAY.PARM' >>batch_files/jscript_$krun

echo 'batch_files/jscript_'${krun}' has been created.'
echo ' ' 
echo 'Now, let us wait for the farms...'
echo ' '
#
# Submit job to the farm
#
jsub batch_files/jscript_$krun
#
echo
echo '***** Good Bye and thank you for using this program *****'
echo
