#!/bin/sh

# Usage: farm_list
#
# This script creates batch_krun and jscript_krun in batch_files directory
# and submits the job to the farms
#
# It assumes to be in the e01011-replay directory and the .tmpl.REPLAY file
# exists
#
# Updates
# November 02, 2006 Include recent changes due to Auger update
# December 09, 2005 Read numbers for gstop
# September 29, 2005 Read run numbers from file
# September 10, 2005 Submit jobs for a range of runs
# July 18, 2005 Validate integer input
# July 10, 2005 Ask for the run number to the user
# July 07, 2005 Victor M. Rodriguez
# Sep. 20, 2009 Zhihong Ye
#
RAWDIR=/w/cache/mss/hallc/hks09/raw/
#
# Check whether the raw data are in cache or not
#
echo '&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&'
echo '& Before you submit the jobs, you need to make sure that the  &'
echo '& raw data are already in the /cache/mss/hallc/hks09/raw/     &'
echo '&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&'
echo ' '
echo 'Are thy already in /cache/mss/? 1->Yes, 0->No or Not Sure'
test=0
read test

if [ "$test" -eq 0 ]
then 
    echo '%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%'
    echo '% Please conform by run:  ifarml3>./farm_cache [runlist] %'
    echo '%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%'
    exit 1
else
    if [ "$test" -eq 1 ]
    then
	clear
	echo
	echo 'Good! Lets start to submit the job!'
	echo
    fi
fi
#
# Function to check if input is an integer
#
is_integer() {
 case $1 in
  *[!0-9]*) return 1;;
  *) return 0;;
 esac
}
#
#Which Target?
#
target='coin'
echo '----------------------------------------------------------------'
echo 'Which Target? '
echo ' EX. (CH2, Li7, Be9, B10, C12, Cr52, SS)'
echo
read target
#
#Which Ntuple?
#
ntuple='coin'
echo '----------------------------------------------------------------'
echo 'Which Ntuple you want to create? '
echo ' For example,if you want to create coinxxxxx.rzdat, type: coin'
echo ' By the way, do not forget to change it in REPLAY.PARAM!'
echo
read ntuple
#
#How many events for each run?
#
more=1
echo '----------------------------------------------------------------'
echo 'What is the MAX events for each run? 1-> 2M, 2-> 4M'
echo
read more
#
# Verify if batch_files and .tmp.REPLAY exist
#
if ! [ -d batch_files ]
    then 
    echo '----------------------------------------------------------------'
    echo 'I need batch_files directory. I am going to create it'
    echo  
    mkdir batch_files
fi
#
# Ask for file name
#
echo '----------------------------------------------------------------'
echo 'Input the file name. It needs a list of run numbers and gstop'
echo
echo -n 'File name: '
read fname
#
home=$PWD                    # The directory where replay_script is
username=${USER}@jlab.org    # email which will be notify when the job is done
#
echo
while read krun
  do
  echo 'Working on run '${krun}
  echo '---------------------'
#
# Write file batch_krun
#
  echo '#!/bin/sh' > batch_files/batch_$krun
  echo 'cd ' $home >>batch_files/batch_$krun
  
# I assume the max events of each run is 2M
  echo ' '>>batch_files/batch_$krun
  echo './replay_script grun='$krun 'gstart=1 gstop=500000' >>batch_files/batch_$krun
  echo 'mv ./paw/'$ntuple$krun'.rzdat ./paw/'$target$krun'_1.rzdat' >>batch_files/batch_$krun
  echo 'h2root ./paw/'$target$krun'_1.rzdat'>>batch_files/batch_$krun
  
  echo ' '>>batch_files/batch_$krun
  echo './replay_script grun='$krun 'gstart=500001 gstop=500000' >>batch_files/batch_$krun
  echo 'mv ./paw/'$ntuple$krun'.rzdat ./paw/'$target$krun'_2.rzdat' >>batch_files/batch_$krun
  echo 'h2root ./paw/'$target$krun'_2.rzdat'>>batch_files/batch_$krun
  
  echo ' '>>batch_files/batch_$krun
  echo './replay_script grun='$krun 'gstart=1000001 gstop=500000' >>batch_files/batch_$krun
  echo 'mv ./paw/'$ntuple$krun'.rzdat ./paw/'$target$krun'_3.rzdat' >>batch_files/batch_$krun
  echo 'h2root ./paw/'$target$krun'_3.rzdat'>>batch_files/batch_$krun
  
  echo ' '>>batch_files/batch_$krun
  echo './replay_script grun='$krun 'gstart=1500001 gstop=500000' >>batch_files/batch_$krun
  echo 'mv ./paw/'$ntuple$krun'.rzdat ./paw/'$target$krun'_4.rzdat' >>batch_files/batch_$krun
  echo 'h2root ./paw/'$target$krun'_4.rzdat'>>batch_files/batch_$krun

# If the max events of each run is 4M
  if [ "$more" -eq 2 ]
      then
      echo ' '>>batch_files/batch_$krun
      echo './replay_script grun='$krun 'gstart=2000001 gstop=500000' >>batch_files/batch_$krun
      echo 'mv ./paw/'$ntuple$krun'.rzdat ./paw/'$target$krun'_5.rzdat' >>batch_files/batch_$krun
      echo 'h2root ./paw/'$target$krun'_5.rzdat'>>batch_files/batch_$krun
      
      echo ' '>>batch_files/batch_$krun
      echo './replay_script grun='$krun 'gstart=2500001 gstop=500000' >>batch_files/batch_$krun
      echo 'mv ./paw/'$ntuple$krun'.rzdat ./paw/'$target$krun'_6.rzdat' >>batch_files/batch_$krun
      echo 'h2root ./paw/'$target$krun'_6.rzdat'>>batch_files/batch_$krun
      
      echo ' '>>batch_files/batch_$krun
      echo './replay_script grun='$krun 'gstart=3000001 gstop=500000' >>batch_files/batch_$krun
      echo 'mv ./paw/'$ntuple$krun'.rzdat ./paw/'$target$krun'_7.rzdat' >>batch_files/batch_$krun
      echo 'h2root ./paw/'$target$krun'_7.rzdat'>>batch_files/batch_$krun
      
      echo ' '>>batch_files/batch_$krun
      echo './replay_script grun='$krun 'gstart=3500001 gstop=500000' >>batch_files/batch_$krun
      echo 'mv ./paw/'$ntuple$krun'.rzdat ./paw/'$target$krun'_8.rzdat' >>batch_files/batch_$krun
      echo 'h2root ./paw/'$target$krun'_8.rzdat'>>batch_files/batch_$krun
  fi 
#  
  chmod +x batch_files/batch_$krun
  
  echo 'batch_files/batch_'${krun}' has been created!'
  echo ' '
#
# Write the jsub script
#
  echo 'PROJECT     e01011' > batch_files/jscript_$krun
  echo 'COMMAND     '$home'/batch_files/batch_'$krun >>batch_files/jscript_$krun
  echo 'JOBNAME     hks.analysis.'${krun} >>batch_files/jscript_$krun
  echo 'TRACK       analysis' >> batch_files/jscript_$krun
  echo 'TIME        4000' >>batch_files/jscript_$krun
  echo 'OS          linux' >>batch_files/jscript_$krun
  echo 'MAIL:       '$username >>batch_files/jscript_$krun
  echo 'INPUT_FILES: '$home'/REPLAY.PARM' >>batch_files/jscript_$krun
  
  echo 'batch_files/jscript_'${krun}' has been created.'
  echo ' ' 
  echo 'Now, let us wait for the farms...'
  echo ' '
#
# Submit job to the farm
 jsub batch_files/jscript_$krun
#
#
  echo 'Job '$krun 'has been submited!'
  echo
  echo
#
  sleep 1
done < $fname
echo
echo '     ***** Good Bye and thank you for using the script *****'
echo
