      subroutine h_tof_fit(trk)

*-------------------------------------------------------------------
* author: John Arrington
* created: 2/22/94
*
* s_tof_fit fits the velocity of the paritcle from the corrected
* times generated by s_tof.
*
* modifications:
* $Log: h_tof_fit.f,v $
* Revision 1.1.1.1  2009/06/23 13:55:44  kawama
*
* e05115 src repository for software development
*
* Revision 1.1.1.1  2005/05/14 21:44:37  miyoshi
*
*
* Revision 1.1.1.1  2004/08/30 21:21:40  miyoshi
* new dir
*
* Revision 2.1  2000/03/17 23:34:01   jinghua
* (JLiu) Changed the local variables to REAL*8. The old version
* with REAL*4 can lead to big errors for some special events.
*
* Revision 2.0  2000/03/10 09:04:21   jinghua
* (JLiu) Modified
*
* Revision 1.6  1996/09/04 20:36:55  saw
* (JRA) Don't forget the  sqrt in pathnorm
*
* Revision 1.5  1995/05/22 19:45:59  cdaq
* (SAW) Split gen_data_data_structures into gen, hms, hks, and coin parts"
*
* Revision 1.4  1995/02/23  13:28:35  cdaq
* (JRA) Add track index to sgood_scin_time
*
* Revision 1.3  1994/11/23  14:15:49  cdaq
* * (SPB) Recopied from hms file and modified names for HKS
*
* Revision 1.2  1994/06/14  04:36:30  cdaq
* (DFG) Protect against divide by 0 in beta calc
*
* Revision 1.1  1994/04/13  18:45:19  cdaq
* Initial revision
*
*-------------------------------------------------------------------

      implicit none

      include 'hks_data_structures.cmn'
      include 'hks_scin_parms.cmn'
      include 'hks_scin_tof.cmn'
      include 'gen_constants.par'
      include 'gen_event_info.cmn'

      character*20 here
      parameter (here = 'h_tof_fit')

      real*8 sumw, sumt, sumz, sumzz, sumtz
      real*8 scin_weight
      real*8 tmp, t0 ,tmpdenom, beta
      real*8 pathnorm
      integer*4 hit, trk
      save

      sumw = 0.
      sumt = 0.
      sumz = 0.
      sumzz = 0.
      sumtz = 0.
      do hit = 1 , hscin_tot_hits
        if (hgood_scin_time(trk,hit)) then
          scin_weight = 1./dble(hscin_sigma(hit))**2
          sumw = sumw + scin_weight
          sumt = sumt + scin_weight * hscin_time(hit)
          sumz = sumz + scin_weight * hscin_zpos(hit)
          sumzz = sumzz + scin_weight * hscin_zpos(hit)**2
          sumtz = sumtz + scin_weight * hscin_zpos(hit) *
     1         hscin_time(hit)
        endif
      enddo
* The formula for beta (and t0) come from taking chi-squared (as
* defined below), and differentiating  with respect to each
* of the fit paramters (beta and t0 for fit to z=beta*(t-t0)).
* Setting both of these derivatives to zero gives the minumum
* chisquared (since they are quadratic in beta and t0), and
* gives a solution for beta in terms of sums of z, t, and w.
      tmp = sumw*sumzz - sumz*sumz
      tmpdenom = sumw*sumtz - sumz*sumt
      if(tmpdenom .ne. 0D0 .and. tmp.ne.0D0) then
        t0 = (sumt*sumzz - sumz*sumtz) / tmp
        beta = tmp / tmpdenom     !velocity in cm/ns.
        hbeta_chisq(trk) = 0.

        do hit = 1 , hscin_tot_hits
          if (hgood_scin_time(trk,hit)) then
            hbeta_chisq(trk) = hbeta_chisq(trk) + 
     1           (hscin_zpos(hit)/beta -
     1           (hscin_time(hit) - t0))**2 / hscin_sigma(hit)**2
          endif
        enddo

        pathnorm = sqrt(1. + hxp_fp(trk)**2 + hyp_fp(trk)**2)
        beta = beta * pathnorm/speed_of_light !take angle into account
        hbeta(trk) = real(beta)
      else
        hbeta(trk) = 0.                 !set unphysical beta
        hbeta_chisq(trk) = -2
      endif                             !end if on denomimator = 0.

      return
      end
